--                                   ........ 
--                              ..,;;;;,;;;;;;,.
--                            ..,...         ..,,.
--                                     ..                  
--                                     :;                    
--                                    .do..                 
--                 .               ...lOkxc...               . 
--              ....            .,,,.:xloOx:.,,..            ....
--             .;.            .,;.  .dl..;oo.  .;,.            .;.
--            ,c.            .:.  .:dc.   .cd;.  ,:.            .:.
--           .c,            .;;.,coc,.;:::,.,col;.:;.            ;c.
--           ,l.      ...,;:oxol:,. .l:..,cl. .,:ldxl:;....      .l,
--           ,c.      ...,::oxdl:.. .l:..,cl. ..:ldxo::,...      .l,
--           .c,            .::.;llc..;::c;..col;,:;             ;c.
--            ,:.            .;.  .:d:.   .:d:.  ,;.            .c, 
--             .;.            .,,.  .dl...lo.  .;,.            .;. 
--              ....            .,,..:xllOx:.,,,.            ....
--                 .               ...lOkkl...               .
--                                    .do,.',
--                                     ::',
--                                     ..',
--                           ...                 ... 
--                            ..,...         ...,.. 
--                              ..,;;;;,,,;;;;,..  
--                                  ......... 
-- DOTFILE FOR NEOVIM
-- https://github.com/Theo-Hafsaoui/dotfile
-- 
-- resulte of the fusion of better dotfile, this neovim instance is even slower than
-- you might think but ehhh, it still 100x faster than emacs.

require('hafsaoui.general')
require('hafsaoui.key')
