# █ █ █▄█ █▀█ █▀█ █   █▀█ █▀▀ █▄▀
# █▀█  █  █▀▀ █▀▄ █▄▄ █▄█ █▄▄ █ █

$wall = /home/anemon/Downloads/lockScreen.jpg

# GENERAL
  hide_cursor = true
  ignore_empty_input = true
  text_trim = true
}

# BACKGROUND
background {
    monitor = 
    path = $wall
}

label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%H")"
    color = rgba(167, 192, 128, 1)
    shadow_size = 3
    shadow_color = rgba(167, 192, 128, 1)
    shadow_boost = 1.2
    font_size = 150
    font_family = AlfaSlabOne 
    position = 750, -250
    halign = center
    valign = top
    zindex = 5
}

# TIME
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%M")"
    color = rgba(167, 192, 128, 1)
    font_size = 150
    font_family = AlfaSlabOne
    position = 750, -420
    halign = center
    valign = top
    zindex = 5
}

label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%d %b %A")"
    color = rgba(122, 132, 120, 1)
    font_size = 14
    font_family = JetBrains Mono Nerd Font Mono ExtraBold
    position = 750, -130
    halign = center
    valign = center
    zindex = 5
}

# INPUT FIELD
input-field {
    monitor =
    size = 200, 50
    outline_thickness = 1
    outer_color = rgba(145, 153, 159, 1)
    dots_size = 0.1 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 1 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    inner_color = rgba(45, 53, 59, 1)
    font_color = rgba(122, 132, 120, 1)
    fade_on_empty = false
    placeholder_text =<i>...</i>
    # invert_numlock = true # change color = rgba(167, 192, 128, 1)
    # capslock_color = rgba(167, 192, 128, 1)
    # numlock_color = rgba(167, 192, 128, 1)
    # bothlock_color = rgba(167, 192, 128, 1)
    hide_input = false
    position = 750, -220
    halign = center
    valign = center
    zindex = 20
}

# Battery
label {
    monitor =
    text = cmd[update:1000] echo -e "$($battery)"
    color = rgba(255, 192, 128, 1)
    font_size = 12
    font_family = JetBrains Mono Nerd Font Mono ExtraBold
    position = -30, -510
    halign = right
    valign = center
    zindex = 5
}

# Battery div
shape {
    monitor =
    size = 70, 35
    color = rgba(250, 192, 128, 1)
    rounding = 10
    rotate = 0
    position = 905, 12
    halign = center
    valign = bottom
    zindex = 1
}
