preload = ~/Downloads/Jacob_van_Ruysdael_-_A_Road_through_an_Oak_Wood_-_Google_Art_Project.jpg
wallpaper = DVI-D-1,~/Downloads/Jacob_van_Ruysdael_-_A_Road_through_an_Oak_Wood_-_Google_Art_Project.jpg
